---
# tasks file for local_accounts
- name: Manage users and groups
  ansible.builtin.include_tasks:
    file: users_and_groups.yml
    apply:
      tags:
        - local_accounts
        - local_users
  when:
    - local_accounts_managed | bool
  tags:
    - local_accounts
    - local_users

- name: Manage ssh keys
  ansible.builtin.include_tasks:
    file: ssh_keys.yml
    apply:
      tags:
        - local_accounts
        - ssh_keys
  when:
    - local_accounts_managed | bool
  tags:
    - local_accounts
    - ssh_keys

- name: Manage .bashrc
  ansible.builtin.include_tasks:
    file: bashrc.yml
    apply:
      tags:
        - local_accounts
        - bashrc
  when:
    - local_accounts_managed | bool
  tags:
    - local_accounts
    - bashrc
...
