---
# sub-tasks for managing huge pages NUMA nodes via writing to the /sys file system.
- name: hugepages_numa_nodes | Convert hugepages_size to kB for path
  ansible.builtin.set_fact:
    hugepages_path: "hugepages-2048kB"
  when:
    - hugepages_size == "2M"

- name: hugepages_numa_nodes | Convert hugepages_size to kB for path
  ansible.builtin.set_fact:
    hugepages_path: "hugepages-1048576kB"
  when:
    - hugepages_size == "1G"

- name: hugepages_numa_nodes | Check current HugePages value and register the result
  ansible.builtin.command: "cat /sys/devices/system/node/{{ hugepages_numa_node_setting.node }}/hugepages/{{ hugepages_path }}/nr_hugepages"
  register: hugepages_current_nr_hugepages_results
  changed_when: false
  loop: "{{ hugepages_numa_node_page_settings }}"
  loop_control:
    loop_var: hugepages_numa_node_setting

- name: hugepages_numa_nodes | Change value if number_of_pages differs
  ansible.builtin.shell: 'set -euxo pipefail && echo "{{ hugepages_current_result.hugepages_numa_node_setting.number_of_pages }}" > /sys/devices/system/node/{{ hugepages_current_result.hugepages_numa_node_setting.node }}/hugepages/{{ hugepages_path }}/nr_hugepages'
  become: true
  loop: "{{ hugepages_current_nr_hugepages_results.results }}"
  loop_control:
    loop_var: hugepages_current_result
  when:
    - hugepages_current_result.hugepages_numa_node_setting.number_of_pages | int != hugepages_current_result.stdout | int
  register: hugepages_change_numa_nodes_result
  changed_when: hugepages_change_numa_nodes_result.rc == 0
...
